name: Run API Tests

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск раз в сутки
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🚀 Установка Newman
        run: |
          npm install -g newman
          echo "Newman установлен"

      - name: 🔍 Запуск API-тестов
        run: |
          newman run postman_collection_auth_fixed.json \
            --reporters cli || echo "Тесты провалены" > failed_tests.txt

      - name: 📡 Отправка отчета в Telegram
        run: |
          MESSAGE="✅ API-тесты успешно пройдены!"
          if [ -f failed_tests.txt ]; then MESSAGE="❌ API-тесты провалены!"; fi
          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/postman-api-tests/"
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE"
