name: Run API Tests  # Название workflow

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск раз в сутки (в 00:00 UTC)
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  test:
    runs-on: ubuntu-latest  # Запуск на Ubuntu

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🚀 Установка Newman и Allure
        run: |
          npm install -g newman newman-reporter-allure allure-commandline
          echo "✅ Newman и Allure установлены"

      - name: 🔍 Проверка переменных окружения
        run: |
          echo "🔍 Проверяем переменные окружения:"
          echo "BASE_URL = ${{ secrets.BASE_URL }}"
          echo "USERNAME = ${{ secrets.USERNAME }}"
          echo "PASSWORD = (скрыто)"
          echo "AUTH_TOKEN = (если пусто, логин не сработал)"

      - name: 📂 Проверка содержимого файла окружения
        run: cat postman_environment.json

      - name: 🔍 Запуск API-тестов
        run: |
          newman run postman_collection_auth_fixed.json \
            --environment postman_environment.json \ 
            --reporters cli,allure \
            --reporter-allure-export allure-results || echo "Тесты провалены" > failed_tests.txt

      - name: 📊 Генерация отчета Allure
        run: |
          allure generate allure-results --clean -o allure-report

      - name: 📤 Загрузка отчета в GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages  # Указываем, куда пушить

      - name: 📡 Отправка отчета в Telegram
        run: |
          MESSAGE="✅ API-тесты успешно пройдены!"
          if [ -f failed_tests.txt ]; then MESSAGE="❌ API-тесты провалены!"; fi
          MESSAGE="$MESSAGE%0A📊 Отчет: https://Farabi001.github.io/postman-api-tests/"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE"
