name: Run API Tests  # Название workflow

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск раз в сутки (в 00:00 UTC)
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  test:
    runs-on: ubuntu-latest  # Запуск на Ubuntu

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🚀 Установка Newman и Allure
        run: |
          npm install -g newman newman-reporter-allure allure-commandline
          echo "✅ Newman и Allure установлены"

      - name: 🔍 Запуск API-тестов
        run: |
          newman run postman_collection_auth_fixed.json \
            --environment Investudy.postman_environment.json \ 
            --reporters cli,allure \
            --reporter-allure-export allure-results || echo "Тесты провалены" > failed_tests.txt || true

      - name: 🔍 Запуск API-тестов
        run: |
          newman run postman_collection_auth_fixed.json \
            --environment postman_environment.json \
            --reporters cli,allure \
            --reporter-allure-export allure-results || echo "Тесты провалены" > failed_tests.txt || true

      - name: 📊 Генерация отчета Allure (всегда)
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report || true

      - name: 📤 Загрузка отчета в GitHub Pages
        if: always()
        run: |
          git checkout --orphan gh-pages
          git --work-tree=allure-report add --all
          git commit -m "Обновлен отчет"
          git push origin HEAD:gh-pages --force || true

      - name: 📡 Отправка отчета в Telegram
        if: always()
        run: |
          MESSAGE="✅ API-тесты успешно пройдены!"
          if [ -f failed_tests.txt ]; then MESSAGE="❌ API-тесты провалены!"; fi
          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/postman-api-tests/"
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=$MESSAGE"
