name: API Tests

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔍 Проверка пути npm-пакетов
        run: |
          echo "🔍 npm root -g:"
          npm root -g

      - name: 🔧 Установка newman и репортеров
        run: |
          echo "🛠 Удаляем старый newman и репортеры..."
          npm uninstall -g newman newman-reporter-html newman-reporter-json || true
          npm cache clean --force
          
          echo "🔧 Устанавливаем заново..."
          npm install -g newman
          npm install -g newman-reporter-html newman-reporter-json

          echo "🔄 Добавляем репортеры в PATH..."
          export NODE_PATH=$(npm root -g)
          export PATH=$NODE_PATH/bin:$PATH
          echo "export NODE_PATH=$(npm root -g)" >> ~/.bashrc
          echo "export PATH=$NODE_PATH/bin:$PATH" >> ~/.bashrc
          source ~/.bashrc

      - name: 🔍 Проверка установленных npm-пакетов
        run: npm list -g --depth=0

      - name: 🔍 Найти путь newman
        run: which newman || echo "❌ newman не найден!"

      - name: 🔍 Проверка доступных репортеров
        run: newman run --help | grep "reporters" || echo "❌ Репортеры не найдены!"

      - name: 🚀 Запуск API-тестов и создание отчетов
        run: |
          mkdir -p public
          echo "🛠 Запускаем newman..."
          newman run postman_collection_auth_fixed.json \
            -e Investudy.postman_environment.json \
            -r html --reporter-html-export=public/report.html \
            -r json --reporter-json-export=newman-report.json \
            -r cli --verbose | tee newman.log || true

      - name: 📂 Проверка наличия отчетов
        run: |
          echo "📂 Проверяем созданные файлы..."
          ls -la public/ || echo "❌ Папка public пуста!"
          ls -la newman-report.json || echo "❌ JSON-отчет не найден!"
          echo "📄 Вывод последних 20 строк newman.log:"
          cat newman.log | tail -20

      - name: 📤 Публикация HTML-отчета на GitHub Pages
        if: always()
        run: |
          if [ -f public/report.html ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git checkout --orphan gh-pages
            git reset --hard
            git clean -fdx
            cp -r public/* .
            git add .
            git commit -m "Обновлен HTML-отчет"
            git push origin HEAD:gh-pages --force || true
          else
            echo "❌ Отчет report.html не найден!"
          fi

      - name: 📡 Отправка отчета в Telegram
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          if [ -f newman-report.json ]; then
            ERRORS=$(jq '[.run.executions[] | select(.assertions[]?.error)] | length' newman-report.json)
            MESSAGE="✅ API-тесты завершены! Количество ошибок: $ERRORS"
          else
            MESSAGE="❌ Ошибка: JSON-отчет newman-report.json не найден!"
          fi

          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/api-tests/report.html"

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "text=$MESSAGE"
