name: API Tests

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔧 Установка зависимостей
        run: npm install -g newman newman-reporter-allure

      - name: 🔍 Проверка файлов перед запуском
        run: |
          pwd
          ls -l
          
      - name: 🚀 Запуск API-тестов
        run: |
          mkdir -p allure-results
          newman run postman_collection_auth_fixed.json \
            -e Investudy.postman_environment.json \
            -r allure --reporter-allure-export=allure-results \
            -r cli --verbose | tee newman.log || true

      - name: 📂 Проверка наличия Allure-результатов
        run: ls -la allure-results || echo "❌ Папка `allure-results` отсутствует!"

      - name: 📊 Генерация отчета Allure
        if: always()
        run: |
          if [ -d allure-results ]; then
            mkdir -p public
            allure generate allure-results --clean -o public || true
          else
            echo "❌ Нет результатов тестов, отчет не создан!"
          fi

      - name: 📤 Публикация отчета на GitHub Pages
        if: always()
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git checkout --orphan gh-pages
          git reset --hard
          git clean -fdx

          cp -r public/* .

          git add .
          git commit -m "Обновлен отчет Allure"
          git push origin HEAD:gh-pages --force || true

      - name: 📡 Отправка отчета в Telegram
        run: |
          MESSAGE="✅ API-тесты успешно пройдены!"
          if grep -q "❌ Ошибка" newman.log; then 
            MESSAGE="❌ Ошибки в API-тестах!"
            ERRORS=$(grep "❌ Ошибка" newman.log | tail -10)
            MESSAGE="$MESSAGE%0A%0A$ERRORS"
          fi
          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/api-tests/"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_GROUP_CHAT_ID }}" \
          -d "text=$MESSAGE"
