name: API Tests

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔧 Установка зависимостей (Newman + Allure)
        run: |
          npm install -g newman newman-reporter-allure
          sudo apt update
          sudo apt install -y openjdk-11-jdk curl unzip

          # Удаляем старые файлы, если они есть
          rm -rf allure.zip /opt/allure

          # Получаем ссылку на последнюю версию Allure
          ALLURE_URL=$(curl -s https://api.github.com/repos/allure-framework/allure2/releases/latest | grep "browser_download_url.*linux.zip" | cut -d '"' -f 4)

          echo "🔽 Скачиваем Allure с $ALLURE_URL..."
          curl -L -o allure.zip "$ALLURE_URL"

          # Проверяем, что файл скачался
          if [ ! -s allure.zip ]; then
            echo "❌ Ошибка: файл Allure.zip пустой!"
            exit 1
          fi

          echo "📂 Распаковываем Allure..."
          unzip allure.zip -d /opt/allure
          sudo mv /opt/allure/allure-*/ /opt/allure/bin

          echo "🔗 Добавляем Allure в PATH..."
          sudo ln -s /opt/allure/bin/bin/allure /usr/local/bin/allure

      - name: 🔍 Проверка установки Allure
        run: |
          which allure || echo "❌ Allure не найден в PATH!"
          allure --version || echo "❌ Allure не установлен!"

      - name: 🚀 Запуск API-тестов
        run: |
          mkdir -p allure-results
          newman run postman_collection_auth_fixed.json \
            -e Investudy.postman_environment.json \
            -r allure --reporter-allure-export=allure-results \
            -r cli --verbose | tee newman.log || true

      - name: 📂 Проверка наличия Allure-результатов
        run: ls -la allure-results || echo "❌ Папка `allure-results` отсутствует!"

      - name: 📊 Генерация отчета Allure
        if: always()
        run: |
          mkdir -p public
          if [ -d allure-results ] && [ "$(ls -A allure-results 2>/dev/null)" ]; then
            /opt/allure/bin/bin/allure generate allure-results --clean -o public || echo "❌ Ошибка генерации отчета!"
          else
            echo "❌ Нет результатов тестов, отчет не создан!"
          fi

      - name: 📤 Публикация отчета на GitHub Pages
        if: always()
        run: |
          if [ "$(ls -A public 2>/dev/null)" ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git checkout --orphan gh-pages
            git reset --hard
            git clean -fdx
            cp -r public/* .
            git add .
            git commit -m "Обновлен отчет Allure"
            git push origin HEAD:gh-pages --force || true
          else
            echo "❌ Папка public пуста, публикация отменена!"
          fi

      - name: 📡 Проверка и отправка отчета в Telegram
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          echo "🔍 Проверка chat_id: '$TELEGRAM_CHAT_ID'"
          if [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "❌ Ошибка: chat_id пустой!"
            exit 1
          fi

          MESSAGE="✅ API-тесты успешно пройдены!"
          if grep -q "❌ Ошибка" newman.log; then 
            MESSAGE="❌ Ошибки в API-тестах!"
            ERRORS=$(grep "❌ Ошибка" newman.log | tail -10)
            MESSAGE="$MESSAGE%0A%0A$ERRORS"
          fi
          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/api-tests/"

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "text=$MESSAGE"
