name: API Tests

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔧 Установка `newman-reporter-html`
        run: |
          echo "🔧 Удаляем кеш npm..."
          npm cache clean --force
          
          echo "🔧 Устанавливаем newman-reporter-html..."
          npm install -g newman-reporter-html || echo "⚠ Не удалось установить глобально, пробуем локально..."
          npm install newman-reporter-html || echo "❌ Локальная установка тоже не удалась!"

      - name: 🔍 Проверка установленных npm-пакетов
        run: npm list -g --depth=0

      - name: 🚀 Запуск API-тестов и создание отчетов
        run: |
          mkdir -p public
          echo "🛠 Запускаем newman..."
          newman run postman_collection_auth_fixed.json \
            -e Investudy.postman_environment.json \
            -r html,json,cli \
            --reporter-html-export="./public/report.html" \
            --reporter-json-export="./public/newman-report.json" \
            --verbose | tee newman.log || true
