name: API Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔍 Запуск API-тестов
        run: |
          newman run postman_collection_auth_fixed.json \
            --environment Investudy.postman_environment.json \
            --reporters cli,allure \
            --reporter-allure-export allure-results || touch failed_tests.txt

      - name: 📊 Генерация отчета Allure (всегда)
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report || true

      - name: 📤 Загрузка отчета в GitHub Pages
        if: always()
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git checkout --orphan gh-pages
          git reset --hard
          git clean -fdx
          
          mkdir -p public
          cp -r allure-report/* public/
          
          git add public
          git commit -m "Обновлен отчет"
          git push origin HEAD:gh-pages --force || true

      - name: 📡 Отправка отчета в Telegram
        if: always()
        run: |
          if [ -f failed_tests.txt ]; then 
            MESSAGE="❌ API-тесты провалены!"; 
          else 
            MESSAGE="✅ API-тесты успешно пройдены!"; 
          fi
          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/postman-api-tests/"
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=$MESSAGE"
