name: API Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Установка зависимостей
        run: npm install -g newman newman-reporter-allure

      - name: 🚀 Запуск API-тестов
        run: |
          newman run postman_collection_auth_fixed.json \
            -e Investudy.postman_environment.json \
            -r allure --reporter-allure-export=allure-results

      - name: 📂 Проверка наличия Allure-результатов
        run: ls -la allure-results || echo "Папка отсутствует"

      - name: 📊 Генерация отчета Allure (всегда)
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report || true

      - name: 📤 Загрузка отчета в GitHub Pages
        if: always()
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git checkout --orphan gh-pages
          git reset --hard
          git clean -fdx
          
          mkdir -p public
          cp -r allure-report/* public/
          
          git add public
          git commit -m "Обновлен отчет"
          git push origin HEAD:gh-pages --force || true
          
      - name: 📡 Отправка отчета в Telegram
        run: |
          MESSAGE="✅ API-тесты успешно пройдены!"
          if grep -q "❌ Ошибка" newman/*.log; then 
            MESSAGE="❌ Ошибки в API-тестах!"
            ERRORS=$(grep "❌ Ошибка" newman/*.log | tail -10)
            MESSAGE="$MESSAGE%0A%0A$ERRORS"
          fi
          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/postman-api-tests/"
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=$MESSAGE"
