name: API Tests

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔍 Проверка установленных npm-пакетов
        run: npm list -g --depth=0 | grep "newman-reporter-html" || echo "❌ Репортер `html` не установлен!"

      - name: 🔧 Установка `newman-reporter-html`
        run: |
          echo "🔧 Устанавливаем newman-reporter-html..."
          npm install -g newman-reporter-html

      - name: 🔍 Проверка доступных репортеров
        run: newman run --help | grep "reporters" || echo "❌ Репортеры не найдены!"

      - name: 🚀 Запуск API-тестов и создание отчетов
        run: |
          mkdir -p public
          echo "🛠 Запускаем newman..."
          newman run postman_collection_auth_fixed.json \
            -e Investudy.postman_environment.json \
            -r html,json,cli \
            --reporter-html-export="./public/report.html" \
            --reporter-json-export="./public/newman-report.json" \
            --verbose | tee newman.log || true

      - name: 📂 Проверка содержимого public/
        run: ls -la public/ || echo "❌ Папка public пуста!"

      - name: 📤 Публикация HTML-отчета на GitHub Pages
        if: always()
        run: |
          if [ -f public/report.html ]; then
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git checkout --orphan gh-pages
            git reset --hard
            git clean -fdx
            cp -r public/* .
            git add .
            git commit -m "Обновлен HTML-отчет"
            git push origin HEAD:gh-pages --force || true
          else
            echo "❌ Отчет report.html не найден!"
          fi

      - name: 📡 Отправка отчета в Telegram
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          if [ -f public/newman-report.json ]; then
            ERRORS=$(jq '[.run.executions[] | select(.assertions[]?.error)] | length' public/newman-report.json)
            MESSAGE="✅ API-тесты завершены! Количество ошибок: $ERRORS"
          else
            MESSAGE="❌ Ошибка: JSON-отчет newman-report.json не найден!"
          fi

          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/api-tests/report.html"

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "text=$MESSAGE"
