name: API Tests

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔍 Проверка установленных npm-пакетов
        run: |
          npm list -g --depth=0 | grep "newman-reporter-html" || echo "❌ Репортер `html` не установлен!"

      - name: 🔧 Установка `newman-reporter-html`
        run: |
          echo "🔧 Устанавливаем newman-reporter-html..."
          npm install -g newman-reporter-html

      - name: 🚀 Запуск API-тестов и создание отчетов
        run: |
          mkdir -p public
          echo "🛠 Запускаем newman..."
          newman run postman_collection_auth_fixed.json \
            -e Investudy.postman_environment.json \
            -r html,json,cli \
            --reporter-html-export="./public/report.html" \
            --reporter-json-export="./public/newman-report.json" \
            --verbose | tee newman.log || true

      - name: 📂 Проверка содержимого public/
        run: ls -la public/ || echo "❌ Папка public пуста!"

      - name: 📡 Отправка отчета в Telegram (файл `report.html`)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "❌ Ошибка: TELEGRAM_BOT_TOKEN или TELEGRAM_CHAT_ID пустые!"
            exit 1
          fi

          if [ -f public/newman-report.json ]; then
            ERRORS=$(jq '[.run.executions[] | select(.assertions[]?.error)] | length' public/newman-report.json)
            MESSAGE="✅ API-тесты завершены! Количество ошибок: $ERRORS"
          else
            MESSAGE="❌ Ошибка: JSON-отчет newman-report.json не найден!"
          fi

          echo "📡 Отправляем сообщение в Telegram..."
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d "chat_id=$TELEGRAM_CHAT_ID" \
            -d "text=$MESSAGE"

          if [ -f public/report.html ]; then
            echo "📎 Отправляем report.html в Telegram..."
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument" \
              -F "chat_id=$TELEGRAM_CHAT_ID" \
              -F "document=@public/report.html" \
              -F "caption=📄 HTML-отчет тестирования"
          else
            echo "❌ Ошибка: report.html не найден!"
            exit 1
          fi
