name: API Tests

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🚀 Запуск API-тестов и создание отчетов
        run: |
          mkdir -p public
          echo "🛠 Запускаем newman..."
          newman run postman_collection_auth_fixed.json \
            -e Investudy.postman_environment.json \
            -r html,json,cli \
            --reporter-html-export="./public/report.html" \
            --reporter-json-export="./public/newman-report.json" \
            --verbose | tee newman.log || true

      - name: 📂 Проверка `newman-report.json`
        run: ls -la public/ || echo "❌ JSON-отчет не найден!"

      - name: 📡 Проверка переменных окружения
        run: |
          echo "🔍 Длина TELEGRAM_BOT_TOKEN: ${#TELEGRAM_BOT_TOKEN} символов"
          echo "🔍 TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: 🔍 Проверка API Telegram
        run: |
          echo "🔗 Запрос к Telegram API:"
          echo "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_CHAT_ID&text=TestMessage"

          curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage?chat_id=$TELEGRAM_CHAT_ID&text=TestMessage" || echo "❌ Ошибка запроса в Telegram!"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: 📡 Отправка отчета в Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "❌ Ошибка: TELEGRAM_BOT_TOKEN или TELEGRAM_CHAT_ID пустые!"
            exit 1
          fi

          if [ -f public/newman-report.json ]; then
            ERRORS=$(jq '[.run.executions[] | select(.assertions[]?.error)] | length' public/newman-report.json)
            MESSAGE="✅ API-тесты завершены! Количество ошибок: $ERRORS"
          else
            MESSAGE="❌ Ошибка: JSON-отчет newman-report.json не найден!"
          fi

          MESSAGE="$MESSAGE%0AОтчет: https://Farabi001.github.io/api-tests/report.html"

          echo "📡 Отправляем отчет в Telegram..."
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d "chat_id=$TELEGRAM_CHAT_ID" \
            -d "text=$MESSAGE" || echo "❌ Ошибка отправки в Telegram!"
