name: API Tests

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🔧 Полная переустановка newman и репортеров
        run: |
          echo "🛠 Удаляем старый newman и репортеры..."
          npm uninstall -g newman newman-reporter-html newman-reporter-json || true
          npm cache clean --force
          
          echo "🔧 Устанавливаем заново..."
          npm install -g newman newman-reporter-html newman-reporter-json

      - name: 🔍 Проверка установленных репортеров
        run: |
          echo "📋 Проверяем список установленных пакетов..."
          npm list -g --depth=0 | grep "newman" || echo "❌ Репортеры не установлены!"

      - name: 🔧 Пересборка npm-пакетов
        run: |
          echo "♻ Пересобираем npm-пакеты..."
          npm rebuild -g newman newman-reporter-html newman-reporter-json

      - name: 🔍 Проверка доступных репортеров
        run: newman -h | grep "reporters" || echo "❌ Репортеры не найдены!"

      - name: 🚀 Запуск API-тестов и создание отчетов
        run: |
          mkdir -p public
          echo "🛠 Запускаем newman..."
          newman run postman_collection_auth_fixed.json \
            -e Investudy.postman_environment.json \
            -r html --reporter-html-export=public/report.html \
            -r json --reporter-json-export=newman-report.json \
            -r cli --verbose | tee newman.log || true

      - name: 📂 Проверка наличия отчетов
        run: |
          echo "📂 Проверяем созданные файлы..."
          ls -la public/ || echo "❌ Папка public пуста!"
          ls -la newman-report.json || echo "❌ JSON-отчет не найден!"
          echo "📄 Вывод последних 20 строк newman.log:"
          cat newman.log | tail -20
